AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String
    AllowedPattern: '[a-z-0-9]+'
    ConstraintDescription: must not contain spaces or uppercase letters.
  TagName1:
    Type: String
  TagName2:
    Type: String


Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${S3BucketName}
      Tags:
        - Key: "SampleProp1"
          Value: !Sub ${TagName1}
        - Key: "SampleProp2"
          Value: !Sub ${TagName2}

Outputs:
  S3BucketName:
    Description: S3 Bucket name for Athena
    Value: !Ref S3BucketName
