name: Cloudformation Template CI

on: 
  push:
    branches: [ main ]
  pull_request:

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository code
        uses: actions/checkout@v3

      - name: Setup CloudFormation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Lint CloudFormation Templates
        run: make lint
