name: Make all change plans

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review]

jobs:
  list-stacks:
    runs-on: ubuntu-latest
    outputs:
      stacks: ${{ steps.changed-stacks.outputs.stacks }}
    steps:
      - name: Check out Repository code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: "**/*.{yaml,yml,properties}"
          files_ignore: .github/workflows/**

      - name: Get changed stacks
        id: changed-stacks
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          #stacks=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | cut -d'/' -f1 | uniq)
          stacks="${{ steps.changed-files.outputs.all_changed_files }}"
          stacks=$(echo ${stacks} | tr ' ' '\n' | cut -d'/' -f1 | uniq)
          stacks=$(echo "[\"${stacks//[[:space:]]/\", \"}\"]")
          echo $stacks
          echo "stacks="$stacks"" >> $GITHUB_OUTPUT

  plan:
    needs: [ list-stacks ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.list-stacks.outputs.stacks) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
          echo "${{ matrix.value }}"

      - name: Check out Repository code
        uses: actions/checkout@v3
        if: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionSessionCTCI
        if: false
 