name: Cloudformation GitOps

on:
  issue_comment:
    types: [created]

jobs:
  issue-command:
    if: ${{ github.event_name == 'issue_comment' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment Trigger
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'cloudformula'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: GitHub API Request
        if: steps.check.outputs.triggered == 'true'
        id: request
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR informations
        if: steps.check.outputs.triggered == 'true'
        id: pr_data
        run: |
          echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
          echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).base.repo.full_name }}"
          echo "::set-output name=repo_clone_url::${{ fromJson(steps.request.outputs.data).base.repo.clone_url }}"
          echo "::set-output name=repo_ssh_url::${{ fromJson(steps.request.outputs.data).base.repo.ssh_url }}"

      - name: clone branch of PR
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.pr_data.outputs.branch }}

      - name: Save comment in file
        if: steps.check.outputs.triggered == 'true'
        run: echo ${{ toJSON(github.event.comment.body) }} > comments/$(date +"%s").txt
